# Source:
# - Dockerfile: https://github.com/bitnami/containers/blob/main/bitnami/postgresql/14/debian-12/Dockerfile
# - documentation: https://github.com/bitnami/containers/blob/main/bitnami/postgresql/README.md

# Usage
# - start container : docker compose --file=docker-compose.exhaust.yml up --detach && docker logs --follow postgresql
# - stop container : docker stop postgresql && docker rm postgresql
# - connect to database : psql --dbname "host=localhost port=5432 user=jane password=password123 dbname=test"
# - connect to database as administrator : psql --dbname "host=localhost port=5432 user=postgres password=password123 dbname=test"
# - connect to container as administrator : docker exec --user root --tty --interactive postgresql bash

# if crash on first run: https://github.com/bitnami/containers/issues/41431

services:
  postgresql:
    container_name: postgresql
    image: docker.io/bitnami/postgresql:14
    restart: no
    volumes:
      - ./database-setup/postgresql.conf:/opt/bitnami/postgresql/conf/conf.d/postgresql.conf
#      Does not work !
#      - https://stackoverflow.com/questions/68801224/install-postgres-extension-into-bitnami-container-as-superuser-on-initial-startu
#      - ./database-setup/startup-script.sql:/docker-entrypoint-initdb.d/startup-script.sql
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_DATABASE=test
      # https://github.com/bitnami/containers/blob/main/bitnami/postgresql/README.md#creating-a-database-user-on-first-run
      - POSTGRESQL_USERNAME=jane
      - POSTGRESQL_PASSWORD=password123
      # https://github.com/bitnami/containers/blob/main/bitnami/postgresql/README.md#creating-a-database-user-on-first-run
      - POSTGRESQL_POSTGRES_PASSWORD=password123
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512m