#https://hub.docker.com/_/postgres
# psql --dbname "host=localhost port=5432 user=postgres password=password123"
version: '2'

services:
  postgresql:
    container_name: postgresql
    image: postgres:16-alpine
    shm_size: 2GB
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password123