#------------------------------------------------------------------------------
#       ---------- PostgreSQL version 18 configuration file        ------------
#------------------------------------------------------------------------------

listen_addresses = '*'

#------------------------------------------------------------------------------
# Libraries
#------------------------------------------------------------------------------

shared_preload_libraries = 'pg_stat_statements'

#------------------------------------------------------------------------------
# Hardware
#------------------------------------------------------------------------------


# https://pgtune.leopard.in.ua/?dbVersion=18&osType=linux&dbType=web&cpuNum=2&totalMemory=8&totalMemoryUnit=GB&connectionNum=&hdType=ssd# DB Version: 18

# OS Type: linux
# DB Type: web
# Total Memory (RAM): 8 GB
# CPUs num: 2
# Data Storage: ssd

#max_connections = 200
#shared_buffers = 2GB
#effective_cache_size = 6GB
#maintenance_work_mem = 512MB
#checkpoint_completion_target = 0.9
#wal_buffers = 16MB
#default_statistics_target = 100
#random_page_cost = 1.1
#effective_io_concurrency = 200
#work_mem = 10082kB
#huge_pages = off
#min_wal_size = 1GB
#max_wal_size = 4GB

max_connections = 200

# shared memory (cache)
shared_buffers = 2GB

# amount of shared memory used for WAL data that has not yet been written to disk
wal_buffers = 16MB

# RAM
effective_cache_size = 6GB

# maintenance workers
maintenance_work_mem = 512MB

# client workers
work_mem = 10082kB

# planner - disc costs
random_page_cost = 1.1
effective_io_concurrency = 200

# for small systems (< 2GB of RAM) may be beneficial to set to “off”
# https://www.postgresql.org/docs/current/runtime-config-resource.html#GUC-HUGE-PAGES
huge_pages = off

#------------------------------------------------------------------------------
# WAL
#------------------------------------------------------------------------------

checkpoint_completion_target = 0.9
wal_level = minimal
max_wal_senders = 0

#------------------------------------------------------------------------------
# Checkpointer
#------------------------------------------------------------------------------

# Checkpoint frequency : set to one day so its does not happens frequently
checkpoint_timeout = 1d
min_wal_size = 1GB
# The size of WAL files that will trigger a checkpoint, regardless of frequency
max_wal_size = 4GB

#------------------------------------------------------------------------------
# Parallelism
#------------------------------------------------------------------------------

#max_parallel_workers_per_gather = 2
#max_parallel_workers = 4
#max_parallel_maintenance_workers = 4

#------------------------------------------------------------------------------
# Statistics
#------------------------------------------------------------------------------
default_statistics_target = 100

#------------------------------------------------------------------------------
# Logging
#------------------------------------------------------------------------------

# https://github.com/darold/pgbadger?tab=readme-ov-file#postgresql-configuration

log_min_duration_statement = 0

log_checkpoints = on
log_connections = on
log_disconnections = on
log_lock_waits = on
log_temp_files = 0
log_autovacuum_min_duration = 0
log_error_verbosity = default

lc_messages='en_US.UTF-8'
lc_messages='C'

logging_collector = on
log_directory = '/logs/postgresql/'
log_filename = 'postgresql.log'
log_line_prefix = '%t [%p]: user=%u,db=%d,app=%a,client=%h'