services:
  swift:
    image: jeantil/openstack-keystone-swift:pike
    container_name: swift-bug
    hostname: swift
    ports:
      - "35357:35357"
      - "8080:8080"
    command: bash -c "rm -v /run/apache2/* ; until curl --silent http://localhost:35357; do sleep 5; done && /swift/bin/register-swift-endpoint.sh http://swift:8080 & /swift/bin/launch.sh"
    healthcheck:
      test: "curl http://localhost:35357"
      interval: 10s
      timeout: 10s
      retries: 15
