GRANT DEBUG CONNECT SESSION TO RDOP;
GRANT DEBUG ANY PROCEDURE TO FAP;


SELECT *
FROM user_sys_privs prv_sys
WHERE 1=1
   AND prv_sys.privilege IN ('DEBUG CONNECT SESSION', 'DEBUG ANY PROCEDURE')
;


SELECT *
FROM 
  user_sys_privs prv_sys
WHERE 1=1
   AND prv_sys.privilege = 'DEBUG CONNECT SESSION'
;
