SET SERVEROUTPUT ON;
DECLARE 
   nom_table VARCHAR2(100);
   action VARCHAR2(100);
   nom_contrainte VARCHAR2(100);
   requete CLOB;
BEGIN

      nom_table := 'TBL_FOO';
      action := 'DISABLE';
      nom_contrainte := 'FK_TBL_FOO';
      
      requete := 'ALTER TABLE ' || nom_table || ' ' || action  || ' CONSTRAINT ' || nom_contrainte;
      dbms_output.put_line(requete);

      EXECUTE IMMEDIATE requete; 
 END;
/    


DECLARE 

   requete CLOB;
   
BEGIN
         
      requete := 'CREATE UNIQUE INDEX "DBOFAP"."SYS_C00503884" ON "DBOFAP"."TBL_TEST" ("BAR") PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE';
      dbms_output.put_line(requete);

      EXECUTE IMMEDIATE requete; 
      
 END;
/   



DECLARE 
BEGIN

  EXECUTE IMMEDIATE'

  CREATE UNIQUE INDEX "DBOFAP"."PK_TBL_TST" ON "DBOFAP"."TBL_TEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1
  MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FAP_DATA"; 

  CREATE UNIQUE INDEX "DBOFAP"."UNIQ_TBL_TEST" ON "DBOFAP"."TBL_TEST" ("FOO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "FAP_DATA"; 
  
 END;
/  
