FROM postgres:alpine
WORKDIR /tmp
RUN  git clone https://github.com/pramsey/pgsql-http.git
COPY --from=intermediate /janakerman/README.md /files/README.md
RUN apk update                                          \
    apk upgrade                                         \
    apk add --update alpine-sdk                         \
    apk add --no-cache bash git openssh make cmake      \
    apk add curl-dev                                    \
    apk add clang                                       \
    apk add llvm9                                       \

RUN make                                                \
    make install