#  https://collabnix.com/how-to-run-oracle-database-in-a-docker-container-using-docker-compose/
#services:
#  oracle:
#    container_name: oracle
#    image: container-registry.oracle.com/database/enterprise:${ORACLE_IMAGE_VERSION}
#    environment:
#      - ORACLE_SID=${ORACLE_SERVICE_IDENTIFIER}
#      - ORACLE_PDB=${ORACLE_SERVICE_NAME}
#      - ORACLE_PWD=${ORACLE_USER_PASSWORD}
#    ports:
#      - "${ORACLE_EXPOSED_PORT}:${ORACLE_INTERNAL_PORT}"
#    healthcheck:
#      test: ["CMD", "sqlplus", "-L", "${ORACLE_USER_NAME}/${ORACLE_USER_PASSWORD}@//localhost:${ORACLE_INTERNAL_PORT}/${ORACLE_SERVICE_IDENTIFIER} as sysdba", "@healthcheck.sql"]
#      interval: 2s
#      timeout: 10s
#      retries: 30


services:
  oracle:
    container_name: oracle
    image: container-registry.oracle.com/database/enterprise:latest
    environment:
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=ORCLPDB1
      - ORACLE_PWD=Oracle_123
    ports:
      - 1521:1521
    volumes:
      - oracle-data:/opt/oracle/oradata
      - oracle-backup:/opt/oracle/backup
    healthcheck:
      test: ["CMD", "sqlplus", "-L", "sys/Oracle_123@//localhost:1521/ORCLCDB as sysdba", "@healthcheck.sql"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  oracle-data:
  oracle-backup:
