start-instance:
    docker compose up --detach --wait

create-start-instance:
    just stop-instance
    just remove-volume
    docker compose up --force-recreate --renew-anon-volumes --remove-orphans --detach --wait
    just grant

stop-instance:
    docker compose down

remove-volume:
    docker volume rm  oracle-free_oracle-volume

console:
    psql --dbname "$CONNECTION_STRING"

logs:
    docker logs --follow oracle

bash:
    docker exec --interactive --tty oracle bash

sqlplus-container:
    docker exec --interactive --tty oracle bash -c "sqlplus username/password@//localhost/FREEPDB1"

sqlplus:
    sqlplus $CONNECTION_STRING @scripts/cli.sql

sqlplus-administrator:
    sqlplus $CONNECTION_STRING_ADMINISTRATOR

sqlplus-administrator-bash:
    docker exec --interactive --tty oracle bash -c "sqlplus sys/administrator_password@//localhost/FREEPDB1 as sysdba"

# 2 minutes, 10 million rows
create-table:
    sqlplus $CONNECTION_STRING @scripts/create-table.sql

query-table:
    sqlplus $CONNECTION_STRING @scripts/query-table.sql

# last one minute
query-table-many-times:
    sqlplus $CONNECTION_STRING @scripts/query-table-many-times.sql

explain:
    sqlplus $CONNECTION_STRING @scripts/explain.sql

grant:
    docker exec --interactive --tty oracle bash -c "sqlplus sys/administrator_password@//localhost/FREEPDB1 as sysdba @/tmp/scripts/grant.sql"

profile-session:
    just create-table
    rm --force ./traces/trace.txt
    sqlplus $CONNECTION_STRING_ADMINISTRATOR @scripts/profile-session.sql
    docker exec --interactive --tty $CONTAINER_NAME /tmp/scripts/process-last-trace.sh
    docker cp $CONTAINER_NAME:/tmp/trace.txt ./traces/trace.txt

trace-identifier:
    just create-table
    sqlplus $CONNECTION_STRING @scripts/profile-identifier.sql

profile-identifier:
    rm --force ./traces/trace.trc
    rm --force ./traces/tkprof/trace.txt
    rm --force ./traces/tvdxtat/trace.txt
    rm --force ./traces/tvdxtat/trace.html
    docker exec --interactive --tty $CONTAINER_NAME /tmp/scripts/process-last-trace.sh
    docker cp $CONTAINER_NAME:/tmp/trace.txt ./traces/tkprof/trace.txt
    docker exec --interactive --tty $CONTAINER_NAME /tmp/scripts/export-last-trace.sh
    docker cp $CONTAINER_NAME:/tmp/trace.trc ./traces/trace.trc
    tvdxtat --input ./traces/trace.trc --output ./traces/tvdxtat/trace.txt  --sys no --wait yes --template text
    tvdxtat --input ./traces/trace.trc --output ./traces/tvdxtat/trace.html --sys no --wait yes --template html