DROP TABLE IF EXISTS foo;
DROP TABLE IF EXISTS bar;

CREATE TABLE foo (id SERIAL);
-- INSERT INTO foo DEFAULT VALUES;
-- SELECT * FROM foo;
-- INSERT INTO foo VALUES (2);

CREATE TABLE bar (id SERIAL);
-- INSERT INTO bar DEFAULT VALUES;
-- SELECT * FROM bar;