DROP TABLE IF EXISTS foo;
DROP TABLE IF EXISTS bar;
DROP TABLE IF EXISTS foobar;

CREATE TABLE foo (id SERIAL PRIMARY KEY );
-- INSERT INTO foo DEFAULT VALUES;
-- SELECT * FROM foo;
-- INSERT INTO foo VALUES (2);

CREATE TABLE bar (id SERIAL PRIMARY KEY );
-- INSERT INTO bar DEFAULT VALUES;
-- SELECT * FROM bar;

CREATE TABLE to_foo (id SERIAL, id_foo INTEGER REFERENCES foo(id));
INSERT INTO to_foo (id_foo) SELECT id FROM foo;
-- SELECT * FROM to_foo;