# https://github.com/docker-library/postgres/blob/c86568af4a6861cb30b8f1b736b0868a3129bdd6/16/bookworm/Dockerfile
# docker compose --file=docker-compose.debian.yml up --detach
# psql --dbname "host=localhost port=5432 user=postgres password=password123"

services:
  postgresql:
    container_name: postgresql-debian
    image: postgres:16-bookworm
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=password123