# Start:
# docker compose up --force-recreate --renew-anon-volumes --detach --wait postgresql
# Connect:
# psql --dbname "host=localhost port=5400 dbname=database user=user password=password"
services:
  postgresql:
    image: postgres:latest
    container_name: postgresql
    ports:
      - "5400:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    healthcheck:
      test: "psql --dbname \"host=localhost port=5432 dbname=database user=user password=password\""
      start_period: 5s
      interval: 1s
      timeout: 2s
      retries: 20