version: '3.7'

services:
   database:
      image: postgres:13-alpine
      container_name: database
      restart: always
      # https://www.postgresql.org/docs/13/runtime-config-client.html#GUC-SHARED-PRELOAD-LIBRARIES
      command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
      environment:
         POSTGRES_DB: database
         POSTGRES_HOST_AUTH_METHOD: trust
      volumes:
         - ./create-schema.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
         - 5432:5432
